services:
  - type: web
    name: smoke-shop-in-a-box
    runtime: static
    staticPublishPath: .
    buildCommand: ""
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /
        destination: /index.html
